config/routes.rb
Rails.application.routes.draw do
  get 'search_group' => 'search#search_group'
  get 'search_room' => 'search#search_room'
  get 'autocomplete_groups' => 'search#autocomplete_groups'
  get 'autocomplete_rooms' => 'search#autocomplete_rooms'
  get 'project' => 'search#about_project'
  post 'places' => 'search#available_places'
  post 'hours' => 'search#available_hours'

   root :to => "search#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
require 'devplan'

class SearchController < ApplicationController

  before_filter :get_groups, only: [ :autocomplete_groups ]
  before_filter :get_rooms, only: [ :autocomplete_rooms ]

  def index
  end

  def about_project
  end

  def search_group
  end

  def search_room
  end

  def available_places

    search_params = params[:search_group]
    ids = search_params[:groups].split(",")
    start_date = search_params[:start_date]
    end_date = search_params[:end_date]
    block_size = search_params[:block_size]
    internal = search_params[:internal]
    @computer_lab = search_params[:computer_lab]

    begin 
      @places = Devplan::Api.instance.available_places(ids, start_date, end_date, block_size, internal)
    rescue
      @alert = 'Wypełnij wszystkie pola.'
    end

  end

  def available_hours

    room_params = params[:search_room]
    @date = room_params[:date]

    begin
      @available_hours = Devplan::Api.instance.available_places(room_params[:room], room_params[:date])
    rescue
      @alert = 'Wypełnij wszystkie pola.'
    end

  end

  def autocomplete_groups
    render json: @groups.map { |g| { name: g.name, id: g.id } }
  end

  def autocomplete_rooms
    render json: @rooms.map { |g| { name: g.full_name, id: g.id } }
  end

  private

    def get_groups
      @groups = Devplan::Api.instance.groups
    end

    def get_rooms
      @rooms = Devplan::Api.instance.places
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Perret</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Perret', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'O projekcie', project_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Szukaj wg grup', search_group_path %></li>
        <li><%= link_to 'Szukaj wg sali', search_room_path %></li>
      </ul>
    </div>
  </div>
</div>
<div class="container">
  <%= yield %>
  <footer>
    <div class="row">
      <div class="col-lg-12">
        <br><br>
        <p>Made by <a href="http://dev.uek.krakow.pl">devTeam</a>.</p>
        <p class="text-muted">
          Aplikacja jest częscią projektu <a href="http://devplan.uek.krakow.pl" target="_blank">devPlan</a>.
        </p>
      </div>
    </div>
  </footer>
</div>
</body>
</html>

app/views/search/about_project.html.erb
<h1>O projekcie</h1>
<p>Projekt Perret powstał w ramach kursu Hurtownie Danych realizowanego przez Uniwersytet Ekonomiczny w Krakowie.</p>
<p>System ten pozwala w łatwy sposób wyszukiwać wszystkie możliwe terminy odrabiania zajęc uwzględniając m.in. zajęcia studentów oraz dostępność sal.</p>
<p>
  Autorzy projektu:
</p>
<ul>
  <li>Maciej Komorowski</li>
  <li>Mateusz Zając</li>
  <li>Robert Dzieża</li>
  <li>Piotr Bałut</li>
  <li>Tomasz Sowa</li>
</ul>

app/views/search/available_hours.erb
<h1>Dostępność sali</h1>
<br>

<script>

    $(document).ready(function() {

        var data = '<%= @available_hours.to_json %>';
        var date = '<%= @date %>';
        data = data.replace(/&quot;/g, '"');
        var parsed_data = [];
        var parsed_data_all = JSON && JSON.parse(data);
        for (var i = 0; i < parsed_data_all.length; i++)
        {
            var day = parsed_data_all[i];
            day.start = date + 'T' + day.starts_at;
            day.end = date + 'T' + day.ends_at;
            day.title = day.starts_at + ' - ' + day.ends_at;
            day.allDay = false;
            parsed_data.push(day);
        }
        data = parsed_data || 0;

                if (data.length == 0) {
            return;
        }

        var months = ['Styczeń', 'Luty', 'Marzec', 'Kwiecień', 'Maj', 'Czerwiec', 'Lipiec',
            'Sierpień', 'Wrzesień', 'Październik', 'Listopad', 'Grudzień'];
        var days = ['Niedziela', 'Poniedziałek', 'Wtorek', 'Środa',
            'Czwartek', 'Piątek', 'Sobota'];
        var date_typeof_date = new Date(date);

        $('#calendar').empty().fullCalendar({
            defaultDate: new Date(date),
            minTime: '07:30:00',
            maxTime: '21:30:00',
            allDaySlot: false,
            start: date_typeof_date,
            monthNames: months,
            monthNamesShort: ['Sty', 'Lut', 'Mar', 'Kwi', 'Maj', 'Cze',
                'Lip', 'Sie', 'Wrz', 'Paź', 'Lis', 'Gru'],
            dayNames: days,
            dayNamesShort: ['Nie', 'Pon', 'Wto', 'Śro',
                'Czw', 'Pią', 'Sob'],
            buttonText:
            {
                today:    'dzisiaj',
                month:    'miesiąc',
                week:     'tydzień',
                day:      'dzień'
            },
            firstDay: 1,
            theme: true,
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'agendaDay'
            },
            defaultView: 'agendaDay',
            height: 'auto',
            slotMinutes: 60,
            dragOpacity: "0.5",
            timeFormat: 'H(:mm)',
            eventLimit: true,
            events: data
        })
    });
</script>
<% if @alert %>
    <div class="alert alert-warning"><%= @alert %></div> 
<% end %>
<div id='calendar'>Brak wyników, <a onclick="window.history.back()">wróć</a>.</div>

app/views/search/available_places.html.erb
<h1>Dostępne miejsca</h1>
<br>

<script>

    $(document).ready(function() {

        var $calendar = $('#calendar');

        var data = '<%= @places.to_json %>';
        var computer_lab = '<%= @computer_lab %>';
        data = data.replace(/&quot;/g, '"');
        var parsed_data = [];
        var parsed_data_all = JSON && JSON.parse(data);
        for (var i = 0; i < parsed_data_all.length; i++)
        {
            var day_data = parsed_data_all[i];
            day_data.allDay = false;
            day_data.title = ' - ' + day_data.ends_at;
            day_data.start = day_data.date + 'T' + day_data.starts_at;
            day_data.end = day_data.date + 'T' + day_data.ends_at;
            day_data.description = 'Wolne sale: <br><br>';
            parsed_data.push(day_data);
            var places = day_data.available_places;

            for (var j = 0; j < places.length; j++)
            {
                if (computer_lab == '1' && !places[j].short_location.contains('lab.'))
                {
                    continue;
                }
                day_data.description += '- ' + places[j].full_location + '<br>';
            }

        }
        data = parsed_data || [];

        if (data.length == 0) {
            return;
        }

        var months = ['Styczeń', 'Luty', 'Marzec', 'Kwiecień', 'Maj', 'Czerwiec', 'Lipiec',
            'Sierpień', 'Wrzesień', 'Październik', 'Listopad', 'Grudzień'];
        var days = ['Niedziela', 'Poniedziałek', 'Wtorek', 'Środa',
            'Czwartek', 'Piątek', 'Sobota'];

        $calendar.empty().fullCalendar({
            defaultDate: new Date(data[0].date),
            monthNames: months,
            monthNamesShort: ['Sty', 'Lut', 'Mar', 'Kwi', 'Maj', 'Cze',
                'Lip', 'Sie', 'Wrz', 'Paź', 'Lis', 'Gru'],
            dayNames: days,
            dayNamesShort: ['Nie', 'Pon', 'Wto', 'Śro',
                'Czw', 'Pią', 'Sob'],
            buttonText:
            {
                today:    'dzisiaj',
                month:    'miesiąc',
                week:     'tydzień',
                day:      'dzień'
            },
            firstDay: 1,
            allDaySlot: false,
            theme: true,
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month, agendaWeek'
            },
            defaultView: 'month',
            height: 500,
            slotMinutes: 15,
            dragOpacity: "0.5",
            timeFormat: 'H(:mm)',
            eventLimit: true,
            editable: true,
            events: data,
            eventClick: function(event) {
                var modal = $("#modal");
                var date = new Date(event.start);
                modal.find(".modal-title").html(days[date.getDay()] + ',  '
                    + date.getUTCDate() + '  ' + months[date.getMonth()]
                    + '   ' + date.getFullYear()
                    + '  (' + date.getUTCHours() + ':' + date.getMinutes()
                    + event.title + ')');
                modal.find(".modal-body").html(event.description);
                modal.modal();
            }
        })
    });
</script>
<% if @alert %>
    <div class="alert alert-warning"><%= @alert %></div> 
<% end %>
<div id='calendar'>Brak wyników, <a onclick="window.history.back()">wróć</a>.</div>
<div class="modal" role="dialog" id="modal">
  <div class="modal-dialog" style="z-index: 9999">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">title</h4>
      </div>
      <div class="modal-body"></div>
      <div class="modal-footer"></div>
    </div>
  </div>
</div>

app/views/search/index.html.erb
<div class="row">
  <div class="col-md-6">
    <h2>Szukaj według grup dziekańskich</h2>
    <p class="lead">Wyszukuj możliwe terminy zajęć oraz sale dla wybranych grup dziekańskich</p>
    <p class="text-justify">Znajdz wszystkie wolne sale w terminie, kiedy wybrane grup dziekańskie nie mają zajęć. Idealne rozwiązanie na wyznaczenie miejsca i terminu "odrobienia" zajęć.</p>
    <p class="text-center">
      <%= link_to 'Szukaj wg grup', search_group_path, {class: 'btn btn-success'} %>
    </p>
  </div><!-- /.col-md-6 -->
  <div class="col-md-6">
    <h2>Wyszukuj według sali</h2>
    <p class="lead">Sprawdź dostępność sali w dogodnym dla siębie terminie</p>
    <p class="text-justify">Wyszukiwanie wolnych sal jeszcze nigdy nie było tak łatwe. Wystarczy, że podasz datę, a nasz system znajdzie wszystkie wolne sale.</p>
    <p class="text-center">
      <%= link_to 'Szukaj wg sali', search_room_path, {class: 'btn btn-success'} %>
    </p>
  </div><!-- /.col-md-6 -->
</div><!-- /.row -->

app/views/search/rooms.erb
<div class="row">
  <div class="col-lg-12">
    <div class="well bs-component">
      <%= simple_form_for :search_room, url: available_hours_path do |p| %>
          <fieldset>
            <legend>Wyszukiwarka</legend>

            <div class="form-group">
              <%= p.input :room, :class => "col-lg-12", placeholder: 'Wyszukaj sali', label: false, :input_html => { :id => 'roomsinput' } %>
            </div>

            <div class="form-group">
              <label class="col-lg-2 control-label">Szukaj dla: </label>
              <div class="col-lg-10">
                <%= p.input :date, :class => "form-control", label: false, placeholder: Time.now.strftime("%Y-%m-%d"), :input_html => { :id => 'start_date_picker' } %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-lg-10 col-lg-offset-2">
                <%= p.button :submit, 'Szukaj', :class => "btn btn-primary" %>
              </div>
            </div>

          </fieldset>
      <% end %>
    </div>
  </div>
</div>

app/views/search/search.html.erb
<div class="row">
 <div class="col-lg-12">
<div class="well bs-component">
  <div class="form-horizontal">
      <%= simple_form_for :search, url: places_path do |p| %>
      <fieldset>
        <legend>Wyszukiwarka</legend>

        <div class="form-group">
          <label class="col-lg-2 control-label">Grupy: </label>
          <div class="col-lg-10">
            <%= p.input :groups, placeholder: 'Wyszukaj grupy', label: false, :input_html => { :id => 'tokeninput', :class => 'col-md-12' } %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-2 control-label">Szukaj od: </label>
          <div class="col-lg-10">
            <%= p.input :start_date, :class => "form-control", label: false, placeholder: Time.now.strftime("%Y-%m-%d"), :input_html => { :id => 'start_date_picker' } %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-2 control-label">Szukaj do: </label>
          <div class="col-lg-10">
            <%= p.input :end_date, :class => "form-control", label: false, placeholder: Time.now.strftime("%Y-%m-%d"), :input_html => { :id => 'end_date_picker' } %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-2 control-label">Ilość wolnych bloków zajęć </label>
          <div class="col-lg-10">
            <%= p.input :block_size, label: false, :class => "form-control", collection: 1..16, selected: 2 %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-2 control-label">Pracownia komputerowa: </label>
          <div class="col-lg-10">
            <%= p.input :computer_lab, as: :boolean, :class => "form-control", label: false, boolean_style: :inline %>
         </div>
        </div>

        <div class="form-group">
          <label class="col-lg-2 control-label">Internal</label>
          <div class="col-lg-10">
            <%= p.input :internal, as: :boolean, boolean_style: :inline, :class => "form-control", label: false, :input_html => { :checked => true } %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <%= p.button :submit, 'Szukaj', :class => "btn btn-primary" %>
          </div>
        </div>

      </fieldset>
      <% end %>
</div>
</div>
   </div>
</div>

app/views/search/search_group.html.erb
<div class="row">
 <div class="col-lg-12">
<div class="well bs-component">
  <div class="form-horizontal">
      <%= simple_form_for :search_group, url: places_path do |p| %>
      <fieldset>
        <legend>Wyszukiwarka</legend>

        <div class="form-group">
          <label class="col-lg-2 control-label">Grupy: </label>
          <div class="col-lg-10">
            <%= p.input :groups, placeholder: 'Podaj nazwę grupy', label: false, :input_html => { :id => 'tokeninput', :class => 'col-md-12' } %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-2 control-label">Szukaj od: </label>
          <div class="col-lg-10">
            <%= p.input :start_date, :class => "form-control", label: false, placeholder: Time.now.strftime("%Y-%m-%d"), :input_html => { :id => 'start_date_picker' } %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-2 control-label">Szukaj do: </label>
          <div class="col-lg-10">
            <%= p.input :end_date, :class => "form-control", label: false, placeholder: Time.now.strftime("%Y-%m-%d"), :input_html => { :id => 'end_date_picker' }%>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-2 control-label">Ilość wolnych bloków zajęć </label>
          <div class="col-lg-10">
            <%= p.input :block_size, label: false, :class => "form-control", collection: 1..16, selected: 2 %>
            <small>45 min odpowiada jednemu blokowi zajęć.</small>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-2 control-label">Pracownia komputerowa: </label>
          <div class="col-lg-10">
            <%= p.input :computer_lab, as: :boolean, :class => "form-control", label: false, boolean_style: :inline %>
         </div>
        </div>

        <div class="form-group">
          <label class="col-lg-2 control-label">Tylko sale w Krakowie</label>
          <div class="col-lg-10">
            <%= p.input :internal, as: :boolean, boolean_style: :inline, :class => "form-control", label: false, :input_html => { :checked => true } %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <%= p.button :submit, 'Szukaj', :class => "btn btn-primary" %>
          </div>
        </div>
      </fieldset>
      <% end %>
</div>
</div>
   </div>
</div>

app/views/search/search_room.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="well bs-component">
      <div class="form-horizontal">
        <%= simple_form_for :search_room, url: hours_path do |p| %>
            <fieldset>
              <legend>Wyszukiwarka</legend>

              <div class="form-group">
                <label class="col-lg-2 control-label">Sala: </label>
                <div class="col-lg-10">
                  <%= p.input :room, placeholder: 'Podaj nazwę sali', label: false, :input_html => { :id => 'roomsinput', :class => 'col-md-12' } %>
                </div>
              </div>

              <div class="form-group">
                <label class="col-lg-2 control-label">Szukaj dla: </label>
                <div class="col-lg-10">
                  <%= p.input :date, :class => "form-control", label: false, placeholder: Time.now.strftime("%Y-%m-%d"), :input_html => { :id => 'start_date_picker' } %>
                </div>
              </div>

              <div class="form-group">
                <div class="col-lg-10 col-lg-offset-2">
                  <%= p.button :submit, 'Szukaj', :class => "btn btn-primary" %>
                </div>
              </div>

            </fieldset>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/about_project.erb
<div class="bs-component">
  <div class="jumbotron">
    <h1>O projekcie</h1>
    <p>Projekt Perret powstał w ramach kursu Hurtownie Danych realizowanego przez Uniwersytet Ekonomiczny w Krakowie.</p>
    <p>System ten pozwala w łatwy sposób wyszukiwać wszystkie możliwe terminy odrabiania zajęc uwzględniając m.in. zajęcia studentów oraz dostępność sal</p>
    <p>
      Skład zespołu projektowego:
      <ul>
        <li>Maciej Komorowski</li>
        <li>Mateusz Zając</li>
        <li>Robert Dzieża</li>
        <li>Piotr Bałut</li>
        <li>Tomasz Sowa</li>
      </ul>
    </p>
  </div>
</div>

app/views/welcome/index.erb
<h1>ALAAA</h1>
<h1>ALAAA</h1>
<h1>ALAAA</h1>
<h1>ALAAA</h1>